"""Record which release each cosplayer, archetype and creature first shipped in.

The three sample galleries can offer a **Newest first** sort, and a "New in
<version>" filter, only because every roster entry carries a release stamp. That
stamp lives in ``data/versions.py``, which this script writes.

Three modes::

    python scripts/stamp_versions.py --check          # CI gate
    python scripts/stamp_versions.py --stamp          # new entries -> this version
    python scripts/stamp_versions.py --from-history   # rebuild from git

``--stamp`` is the one a maintainer runs. It reads the version out of
``pyproject.toml`` and gives it to every entry the map does not already know, so
adding content stays a two-command habit rather than a bookkeeping chore: add the
records, run ``--stamp``. **Entries already stamped are never rewritten** -- a
release date is a fact about the past, and rewriting one would silently reorder
the gallery.

``--from-history`` reconstructs the whole map by reading the data layer out of git
at the tip commit of each past release. It was used once, to seed the file, and
stays because a seed you cannot reproduce is a seed you cannot check.

``--check`` is what CI runs. It fails when a shipped entry has no stamp, and when
the map still names something the pack no longer ships -- the half a convention
alone cannot enforce, since an unstamped entry would simply sort as though it had
always been there.

**Everything here reads the data layer with ``ast``, never by importing it.** The
data modules merge the maintainer's local ``user_options.json`` at import time
(``apply_user_cosplayers`` and friends at the bottom of each), so an import-based
generator would bake private entries into a committed, published file -- the trap
``scripts/generate_js_data.py`` documents at length. Parsing the source sees only
what is written in it. It also makes ``--from-history`` cheap: no subprocess and
no import per revision, just ``git show`` piped through ``ast``.

A user-added entry therefore never gets a stamp, and the gallery treats an
unstamped entry as oldest -- it sorts last under "Newest first" and never appears
under "New in <version>". That is the right failure mode: a user entry has no
image on ``gh-pages`` either.
"""

from __future__ import annotations

import argparse
import ast
import re
import subprocess
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
if str(ROOT) not in sys.path:
    sys.path.insert(0, str(ROOT))

TARGET = ROOT / "data" / "versions.py"
PYPROJECT = ROOT / "pyproject.toml"

#: kind -> (source file, the module-level dict whose KEYS are the entry names).
#: The gallery calls these "cosplay" / "archetypes" / "creatures"; the names here
#: match ``data/`` rather than the gallery folders, and ``GALLERY_KIND`` below maps
#: between them.
SOURCES: dict[str, tuple[str, str]] = {
    "cosplayers": ("data/cosplayers.py", "COSPLAYERS"),
    "archetypes": ("data/templates.py", "ARCHETYPES"),
    "creatures": ("data/creatures.py", "CREATURES"),
    # The fetish and nudity galleries showcase the engine itself (one render
    # per explicit act / per tier pool value); their rosters are the gallery
    # modules, keyed the same way (a module-level dict) as the rest.
    "fetish": ("gallery/fetish_roster.py", "ENTRIES"),
    "nudity": ("gallery/nudity_roster.py", "ENTRIES"),
}

#: gallery folder name -> key in :data:`SOURCES`. ``build_manifest.py`` uses this.
GALLERY_KIND: dict[str, str] = {
    "cosplay": "cosplayers",
    "fetish": "fetish",
    "nudity": "nudity",
    "archetypes": "archetypes",
    "creatures": "creatures",
}

#: Dropdown sentinels are not entries and never have an image or a stamp. Kept in
#: step with the same set in each ``gallery/*/build_manifest.py``.
SENTINELS = {"None", "Random - any", "Random - female", "Random - male",
             "Random — any", "Random — female", "Random — male"}

HEADER = '''"""When each roster entry first shipped, by release.

Generated by ``scripts/stamp_versions.py``. Do not edit by hand -- run::

    python scripts/stamp_versions.py --stamp

after adding cosplayers, archetypes or creatures, and CI will confirm it.

This exists so the sample galleries can answer "what is new in this release?"
without a human keeping a changelog of thousands of tiles in their head.

**It is presentation data only.** Nothing here reaches a prompt, and no seed, saved
workflow, dropdown order or gallery image depends on it -- which is why adding a
release stamp can never change what the node generates.
"""

from __future__ import annotations

#: Every release that has shipped roster content, oldest first. The galleries rank
#: by POSITION IN THIS TUPLE rather than by parsing the version strings, because
#: "0.10.0" sorts before "0.9.0" as text.
RELEASES: tuple[str, ...] = (
'''


def read_version(text: str) -> str:
    match = re.search(r'(?m)^version\s*=\s*"([^"]+)"', text)
    return match.group(1) if match else ""


def current_version() -> str:
    version = read_version(PYPROJECT.read_text(encoding="utf-8"))
    if not version:
        raise SystemExit("could not read version from pyproject.toml")
    return version


def entry_names(source: str, dict_name: str) -> list[str]:
    """Top-level keys of ``dict_name`` in ``source``, read with ``ast``.

    Returns ``[]`` when the module or the dict does not exist, which is what makes
    ``--from-history`` tolerate early releases that predate a data module.
    """
    try:
        tree = ast.parse(source)
    except SyntaxError:
        return []
    for node in ast.walk(tree):
        target = None
        if isinstance(node, ast.AnnAssign):
            target = getattr(node.target, "id", "")
        elif isinstance(node, ast.Assign) and len(node.targets) == 1:
            target = getattr(node.targets[0], "id", "")
        if target != dict_name or not isinstance(node.value, ast.Dict):
            continue
        return [k.value for k in node.value.keys
                if isinstance(k, ast.Constant) and isinstance(k.value, str)
                and k.value not in SENTINELS]
    return []


def shipped_ids() -> dict[str, list[str]]:
    """The entries the pack ships right now, per kind."""
    out: dict[str, list[str]] = {}
    for kind, (relative, dict_name) in SOURCES.items():
        path = ROOT / relative
        text = path.read_text(encoding="utf-8") if path.is_file() else ""
        out[kind] = entry_names(text, dict_name)
    return out


def load_map() -> tuple[list[str], dict[str, dict[str, str]]]:
    empty = {kind: {} for kind in SOURCES}
    if not TARGET.is_file():
        return [], empty
    namespace: dict = {}
    exec(compile(TARGET.read_text(encoding="utf-8"), str(TARGET), "exec"), namespace)
    added = namespace.get("ADDED_IN", empty)
    for kind in SOURCES:
        added.setdefault(kind, {})
    return list(namespace.get("RELEASES", ())), added


def render(releases: list[str], added: dict[str, dict[str, str]]) -> str:
    out = [HEADER]
    for release in releases:
        out.append('    "%s",\n' % release)
    out.append(")\n\n")
    out.append("#: Entry name -> the release it first shipped in.\n")
    out.append("ADDED_IN: dict[str, dict[str, str]] = {\n")
    for kind in SOURCES:
        out.append('    "%s": {\n' % kind)
        for name in sorted(added.get(kind, {})):
            out.append('        %r: "%s",\n' % (name, added[kind][name]))
        out.append("    },\n")
    out.append("}\n")
    return "".join(out)


# ---------------------------------------------------------------------------
# History reconstruction
# ---------------------------------------------------------------------------

# ``encoding="utf-8"`` on both, and it is load-bearing rather than tidiness.
# ``text=True`` alone decodes with the LOCALE codec, which on a Windows box is
# cp1252 -- so `Día de los Muertos` came back as `DÃ­a de los Muertos`, matched no
# current entry, and the archetype was re-stamped as brand new in the release the
# rebuild happened to run in. Caught because the live manifest reported one
# unexpected "new" archetype. Any accented roster name would hit this.
def _git(*args: str) -> str:
    return subprocess.run(["git", *args], cwd=ROOT, capture_output=True,
                          text=True, encoding="utf-8", check=True).stdout


def _show(sha: str, path: str) -> str:
    result = subprocess.run(["git", "show", f"{sha}:{path}"], cwd=ROOT,
                            capture_output=True, text=True, encoding="utf-8",
                            check=False)
    return result.stdout if result.returncode == 0 else ""


def from_history() -> tuple[list[str], dict[str, dict[str, str]]]:
    """Attribute every shipped entry to the EARLIEST release that contained it."""
    shas = _git("log", "--format=%H", "--reverse").split()
    # The tip commit of each release is the one that says what that release shipped.
    # A version that reappears later keeps its first position in the order and its
    # latest content.
    order: list[str] = []
    tip: dict[str, str] = {}
    for sha in shas:
        version = read_version(_show(sha, "pyproject.toml"))
        if not version:
            continue
        if version not in order:
            order.append(version)
        tip[version] = sha

    added: dict[str, dict[str, str]] = {kind: {} for kind in SOURCES}
    releases: list[str] = []
    for version in order:
        found = False
        for kind, (relative, dict_name) in SOURCES.items():
            for name in entry_names(_show(tip[version], relative), dict_name):
                added[kind].setdefault(name, version)
                found = True
        if found:
            releases.append(version)
        print(f"  {version}: {sum(len(v) for v in added.values())} entries known")
    return releases, added


# ---------------------------------------------------------------------------

def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    group = parser.add_mutually_exclusive_group(required=True)
    group.add_argument("--check", action="store_true",
                       help="Verify every shipped entry is stamped (CI gate).")
    group.add_argument("--stamp", action="store_true",
                       help="Stamp new entries with the current version.")
    group.add_argument("--from-history", action="store_true",
                       help="Rebuild the whole map from git history.")
    args = parser.parse_args()

    shipped = shipped_ids()

    if args.from_history:
        releases, added = from_history()
        version = current_version()
        if version not in releases:
            releases.append(version)
        for kind, names in shipped.items():
            for name in names:
                added[kind].setdefault(name, version)
        for kind in added:
            added[kind] = {k: v for k, v in added[kind].items()
                           if k in set(shipped[kind])}
        TARGET.write_text(render(releases, added), encoding="utf-8", newline="\n")
        print(f"Written: data/{TARGET.name} ({len(releases)} releases)")
        return 0

    releases, added = load_map()

    if args.stamp:
        version = current_version()
        new = 0
        for kind, names in shipped.items():
            for name in names:
                if name not in added[kind]:
                    added[kind][name] = version
                    new += 1
        # Drop anything the pack no longer ships (a rename, a deletion). The stamp
        # is keyed on the DISPLAY NAME, which is also how gallery images are keyed,
        # so a rename is a new entry on both sides -- consistently.
        removed = 0
        for kind in added:
            keep = {k: v for k, v in added[kind].items() if k in set(shipped[kind])}
            removed += len(added[kind]) - len(keep)
            added[kind] = keep
        if new and version not in releases:
            releases.append(version)
        TARGET.write_text(render(releases, added), encoding="utf-8", newline="\n")
        print(f"Stamped {new} new entr{'y' if new == 1 else 'ies'} as {version}"
              f"{f'; dropped {removed} no longer shipped' if removed else ''}.")
        return 0

    # --check
    problems: list[str] = []
    for kind, names in shipped.items():
        known = added.get(kind, {})
        for name in names:
            if name not in known:
                problems.append(f"{kind}: {name!r} has no release stamp")
        for name in known:
            if name not in set(names):
                problems.append(f"{kind}: {name!r} is stamped but no longer ships")
    unknown = [r for kind in added for r in added[kind].values() if r not in releases]
    if unknown:
        problems.append(f"stamps name {len(unknown)} release(s) missing from RELEASES")
    if problems:
        print(f"data/versions.py is out of date ({len(problems)} problem(s)):")
        for problem in problems[:20]:
            print(f"  - {problem}")
        if len(problems) > 20:
            print(f"  ... and {len(problems) - 20} more")
        print("\nRun: python scripts/stamp_versions.py --stamp")
        return 1
    total = sum(len(v) for v in added.values())
    print(f"data/versions.py is in sync ({total} entries, {len(releases)} releases).")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
